# Generated by Django 4.2 on 2025-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.CharField(default='Sample Bug', max_length=100),
        ),
    ]
