# Generated by Django 4.2 on 2025-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0002_bug_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
