# Generated by Django 4.2 on 2025-05-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0004_alter_bug_status_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('edit_user_profile_perm', 'can edit user profile')]},
        ),
    ]
