# Generated by Django 4.2 on 2025-05-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0007_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('edit_user_profile_perm', 'EDIT USER PROFILE')]},
        ),
    ]
