# Generated by Django 4.2 on 2025-05-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('edit_user_profile_perm', 'EDIT USER PROFILE'), ('do_something', 'Do Something')]},
        ),
    ]
