# Generated by Django 5.2.1 on 2025-05-30 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0010_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='bug',
            name='platform',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Web', 'Web'), ('iOS', 'iOS')], default='Windows', max_length=20),
        ),
        migrations.AddField(
            model_name='bug',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('developers', models.ManyToManyField(related_name='developer_sprints', to=settings.AUTH_USER_MODEL)),
                ('lead_developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_sprints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='django_bugapp.sprint'),
        ),
    ]
