# Generated by Django 5.2.1 on 2025-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bugapp', '0011_remove_bug_contact_number_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
    ]
